service: photographic

image: photographic/photographic

servers:
  - TARGET_SERVER

registry:
  server: registry.digitalocean.com
  username:
    - MRSK_REGISTRY_TOKEN
  password:
    - MRSK_REGISTRY_TOKEN

env:
  secret:
    - DB_NAME
    - DB_USER
    - DB_HOST
    - DB_PORT
    - MEDIA_ROOT
    - MEDIA_URL
    - STATIC_ROOT
    - STATIC_URL
    - SECRET_KEY
    - DB_PASSWORD

healthcheck:
  path: /up/
  port: 8000
